FirstWeb/Controllers/DangXuatController.cs
using Microsoft.AspNetCore.Mvc;

namespace FirstWeb.Controllers
{
    public class DangXuatController : Controller
    {
        public IActionResult DangXuat()
        {
            HttpContext.Session.Remove("User");
            return RedirectToAction("DangNhapView", "DangNhap");
        }
    }
}

FirstWeb/Controllers/GioHangController.cs
using FirstWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FirstWeb.Views;
using FirstWeb.Repositories;

namespace FirstWeb.Controllers
{
    public class GioHangController : Controller
    {
        private readonly IStudentRepository<Student> _studentRepository;
        private readonly IMajorRepository<Major> _majorRepository;

        public GioHangController(IStudentRepository<Student> studentRepository, IMajorRepository<Major> majorRepository)
        {
            this._studentRepository = studentRepository;
            this._majorRepository = majorRepository;
        }

        public async Task<IActionResult> GioHangView()
        {
            // Lấy danh sách sinh viên từ session
            var students = HttpContext.Session.GetObjectFromJson<List<Student>>("Students") ?? new List<Student>();
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View(students);
        }

        // POST: GioHang/Add
        [HttpPost, ActionName("Add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("maSV")] string maSV)
        {
            // Lấy sinh viên từ repository bằng id
            Student student = await _studentRepository.GetByIdAsync(maSV);
            if (student == null)
            {
                return NotFound();
            }

            // Lấy danh sách sinh viên từ session
            var students = HttpContext.Session.GetObjectFromJson<List<Student>>("Students") ?? new List<Student>();

            // Kiểm tra xem sinh viên đã có trong danh sách session chưa
            if (!students.Any(s => s.maSV == maSV))
            {
                student.soDiemCong = 1;
                students.Add(student);
                HttpContext.Session.SetObjectAsJson("Students", students);
            }
            else
            {
                var studentFirst = students.FirstOrDefault(s => s.maSV == maSV);
                if (studentFirst != null)
                {
                    studentFirst.soDiemCong += 1; // Đổi tên thành "A"
                    HttpContext.Session.SetObjectAsJson("Students", students);
                }
            }

            // Chuyển hướng về action Index của GioHangController
            return RedirectToAction("GioHangView");
        }

        [HttpPost, ActionName("ClearAll")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClearAll()
        {
            HttpContext.Session.Remove("Students"); 
            return RedirectToAction("GioHangView");
        }

       
    }
}

FirstWeb/Controllers/LichSuController.cs
using FirstWeb.Models;
using FirstWeb.Views;
using Microsoft.AspNetCore.Mvc;

namespace FirstWeb.Controllers
{
    public class LichSuController : Controller
    {
        private readonly IHistoryRepository<Student> _studentRepository;
        private readonly IMajorRepository<Major> _majorRepository;

        public LichSuController(IHistoryRepository<Student> studentRepository, IMajorRepository<Major> majorRepository)
        {
            this._studentRepository = studentRepository;
            this._majorRepository = majorRepository;
        }

        public async Task<IActionResult> LichSuView()
        {
            IEnumerable<Student> students = await _studentRepository.GetAllAsync();
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View(students);
        }
        [HttpPost, ActionName("DuoiHoc")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DuoiHoc(Student student)
        {
            var user = HttpContext.Session.GetObjectFromJson<Login>("User");
            if(user == null)
            {
                return RedirectToAction("DangNhapView", "DangNhap");
            }
            else
            {
                var students = HttpContext.Session.GetObjectFromJson<List<Student>>("Students") ?? new List<Student>();
                foreach (var item in students)
                {
                    await _studentRepository.AddAsync(item);
                }
                HttpContext.Session.Remove("Students");
            }
            
            return RedirectToAction("LichSuView");
        }

    }
}

FirstWeb/Controllers/TimKiemTheoMaController.cs
using FirstWeb.Models;
using FirstWeb.Views;
using Microsoft.AspNetCore.Mvc;

namespace FirstWeb.Controllers
{
    public class TimKiemTheoMaController : Controller
    {
        private readonly IStudentRepository<Student> _studentRepository;
        private readonly IMajorRepository<Major> _majorRepository;

        public TimKiemTheoMaController(IStudentRepository<Student> studentRepository, IMajorRepository<Major> majorRepository)
        {
            this._studentRepository = studentRepository;
            this._majorRepository = majorRepository;
        }
        public async Task<IActionResult> TimKiemTheoMaView([Bind("maNganh, index")] string maNganh, int index)
        {
            IEnumerable<Student> studentList;
            
            if (!string.IsNullOrEmpty(maNganh))
            {
                HttpContext.Session.SetObjectAsJson("Major", maNganh);
                //sử lí tổng trang 
                var totalTask = _studentRepository.GetNumMarjorItemAsync(maNganh);
                var total = await totalTask;
                var endPage = (total % 4 == 0) ? total / 4 : (total / 4) + 1;
                var students = await _studentRepository.GetAllMajorAsync(maNganh, index);
                studentList = students.ToList();
                //truyền dữ liệu
                TempData["endPage2"] = endPage;
                //students = await _studentRepository.GetSearchMaNganhAsync(maNganh);
            }
            else 
            {
                var major = HttpContext.Session.GetObjectFromJson<String>("Major");
                var totalTask = _studentRepository.GetNumMarjorItemAsync(major);
                var total = await totalTask;
                var endPage = (total % 4 == 0) ? total / 4 : (total / 4) + 1;
                var students = await _studentRepository.GetAllMajorAsync(major, index);
                studentList = students.ToList();
                //truyền dữ liệu
                TempData["endPage2"] = endPage;
            }
           
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View(studentList);
        }

    }
}

FirstWeb/Views/Shared/_Layout.cshtml
@{
    var majors = ViewBag.Majors as IEnumerable<FirstWeb.Models.Major>;
    
 
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - FirstWeb</title>

    <link rel="stylesheet" href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/scriphome.js"></script>
</head>
<body >
    <header>
        @{

            var user = Context.Session.GetObjectFromJson<Login>("User");

        }
        @if(user != null)
        {
            <nav class="navbar navbar-inverse" style="position: fixed; width: 100%">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">WebSiteName</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li class="active"><a a asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                        <li><a asp-controller="GioHang" asp-action="GioHangView">Giỏ Sinh Viên</a></li>
                        <li><a asp-controller="LichSu" asp-action="LichSuView">Lịch sử</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form asp-controller="TimKiemTheoTen" asp-action="TimKiemTheoTenView" class="form-inline centered-form" method="post">
                                <input type="text" class="form-control" placeholder="Nhập tên cần tìm kiếm.." name="ten" value="@ViewBag.Search">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                            </form>
                        </li>
                        <li>
                            <a>
                                Xin Chào: @user.taiKhoan
                            </a>
                        </li>       
                        <li><a asp-controller="DangXuat" asp-action="DangXuat"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                    </ul>
                </div>
            </nav>
        }
        else
        {
            <nav class="navbar navbar-inverse" style="position: fixed; width: 100%">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">WebSiteName</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li class="active"><a a asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                        <li><a asp-controller="GioHang" asp-action="GioHangView">Giỏ Sinh Viên</a></li>
                        <li><a asp-controller="LichSu" asp-action="LichSuView">Lịch sử</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form asp-controller="TimKiemTheoTen" asp-action="TimKiemTheoTenView" class="form-inline centered-form" method="post">
                                <input type="text" class="form-control" placeholder="Nhập tên cần tìm kiếm.." name="ten" value="@ViewBag.Search">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                            </form>
                        </li>
                        <li>
                            <a asp-controller="DangNhap" asp-action="DangNhapView">
                                <span class="glyphicon glyphicon-user"></span> Login
                            </a>
                        </li>
                        <li><a asp-controller="DangKy" asp-action="DangKyView"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
                    </ul>
                </div>
            </nav>
        }

    </header>
   
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <div class="sidebar">
                    <table class="table table-hover">
                        <tbody>
                            @foreach (var major in majors)
                            {
                                <tr>
                                    <td>
                                        <a asp-controller="TimKiemTheoMa" asp-action="TimKiemTheoMaView" asp-route-maNganh="@major.maNganh">
                                            @major.tenNganh
                                        </a>
                                    </td>
                                </tr>
                            }                            
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="col-9">
                <div class="main">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>

    </div>


    <footer class="border-top footer text-muted" style="position: fixed">
        <div class="container">
            &copy; 2024 - FirstWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sidebar.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>