FirstWeb/Controllers/GioHangController.cs
using FirstWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FirstWeb.Views;
using FirstWeb.Repositories;

namespace FirstWeb.Controllers
{
    public class GioHangController : Controller
    {
        private readonly IStudentRepository<Student> _studentRepository;
        private readonly IMajorRepository<Major> _majorRepository;

        public GioHangController(IStudentRepository<Student> studentRepository, IMajorRepository<Major> majorRepository)
        {
            this._studentRepository = studentRepository;
            this._majorRepository = majorRepository;
        }

        public async Task<IActionResult> GioHangView()
        {
            // Lấy danh sách sinh viên từ session
            var students = HttpContext.Session.GetObjectFromJson<List<Student>>("Students") ?? new List<Student>();
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View(students);
        }

        // POST: GioHang/Add
        [HttpPost, ActionName("Add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("maSV")] string maSV)
        {
            // Lấy sinh viên từ repository bằng id
            Student student = await _studentRepository.GetByIdAsync(maSV);
            if (student == null)
            {
                return NotFound();
            }

            // Lấy danh sách sinh viên từ session
            var students = HttpContext.Session.GetObjectFromJson<List<Student>>("Students") ?? new List<Student>();

            // Kiểm tra xem sinh viên đã có trong danh sách session chưa
            if (!students.Any(s => s.maSV == maSV))
            {
                student.soDiemCong = 1;
                students.Add(student);
                HttpContext.Session.SetObjectAsJson("Students", students);
            }
            else
            {
                var studentFirst = students.FirstOrDefault(s => s.maSV == maSV);
                if (studentFirst != null)
                {
                    studentFirst.soDiemCong += 1; // Đổi tên thành "A"
                    HttpContext.Session.SetObjectAsJson("Students", students);
                }
            }

            // Chuyển hướng về action Index của GioHangController
            return RedirectToAction("GioHangView");
        }

        [HttpPost, ActionName("ClearAll")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClearAll()
        {
            HttpContext.Session.Remove("Students"); 
            return RedirectToAction("GioHangView");
        }

       
    }
}

FirstWeb/Controllers/StudentController.cs
using DotNetOpenAuth.OpenId.Extensions.SimpleRegistration;
using FirstWeb.Models;
using FirstWeb.Repositories;
using FirstWeb.Views;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FirstWeb
{
    public class StudentController : Controller
    {
        private readonly IStudentRepository<Student> _studentRepository;
        private readonly IMajorRepository<Major> _majorRepository;
        private readonly IHistoryRepository<Student> _historyRepository;
        private readonly IWebHostEnvironment _environment;
        public StudentController(IWebHostEnvironment environment, IStudentRepository<Student> studentRepository, IMajorRepository<Major> majorRepository, IHistoryRepository<Student> historyRepository)
        {
            this._studentRepository = studentRepository;
            this._majorRepository = majorRepository;
            this._historyRepository = historyRepository;
            this._environment = environment;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
          
            return View();
        }

        // GET: HomeController1/GetStudents
        public async Task<ActionResult> GetStudents()
        {
            // var students = await _studentRepository.GetAllAsync();
            /*var totalTask = _studentRepository.GetAllNumItemAsync();
            var total = await totalTask;
            var endPage = (total % 6 == 0) ? total / 6 : (total / 6) + 1;
            var students = await _studentRepository.GetAllItemAsync(endPage);

            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            TempData["endPage"] = endPage;
            var studentList = students.ToList();*/
           
            // Trả về view với danh sách sinh viên
            return View();
        }

        // GET: HomeController1/Details/5
        public async Task<ActionResult> Details(string maSV)
        {
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            if (string.IsNullOrEmpty(maSV))
            {
                return RedirectToAction("Index", "Home");
            }
            var student = await _studentRepository.GetByIdAsync(maSV);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // GET: HomeController1/Create
        public async Task<ActionResult> Create()
        {
            Student student = new Student();
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View(student);
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Student student)
        {
            if (ModelState.IsValid)
            {
                if (student.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(student.ImageUpload.FileName);
                    string extension = Path.GetExtension(student.ImageUpload.FileName);
                    fileName = fileName + extension;

                    // Tạo đường dẫn tuyệt đối tới thư mục lưu file trên server
                    string filePath = Path.Combine(_environment.WebRootPath, "anh", fileName);

                    // Lưu file lên server
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await student.ImageUpload.CopyToAsync(stream);
                    }

                    // Lưu đường dẫn tương đối của file vào thuộc tính Image của student
                    student.image = "anh/" + fileName;

                }
                await _studentRepository.AddAsync(student);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // GET: HomeController1/Edit/5
        public async Task<ActionResult> Edit(string maSV)
        {
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            if (maSV == null)
            {
                return NotFound();
            }

            var student = await _studentRepository.GetByIdAsync(maSV);
            if (student == null)
            {
                return NotFound();
            }
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View(student);
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Student student)
        {
           
            if (student.ImageUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(student.ImageUpload.FileName);
                string extension = Path.GetExtension(student.ImageUpload.FileName);
                fileName = fileName + extension;

                // Tạo đường dẫn tuyệt đối tới thư mục lưu file trên server
                string filePath = Path.Combine(_environment.WebRootPath, "anh", fileName);

                // Lưu file lên server
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await student.ImageUpload.CopyToAsync(stream);
                }

                // Lưu đường dẫn tương đối của file vào thuộc tính Image của student
                student.image = "anh/" + fileName;

            }
            else
            {
                var _sutudent = await _studentRepository.GetByIdAsync(student.maSV);
                student.image = _sutudent.image;
            }
            await _studentRepository.UpdateAsync(student);
            return RedirectToAction("Index", "Home");
        }


        // GET: HomeController1/Delete/5
        public async Task<IActionResult> Delete([Bind("maSV")] string maSV)
        {
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            if (string.IsNullOrEmpty(maSV))
            {
                return RedirectToAction(nameof(Delete));
            }

            var student = await _studentRepository.GetByIdAsync(maSV);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: HomeController1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string maSV)
        {
            await _studentRepository.DeleteAsync(maSV);
            return RedirectToAction("Index", "Home");
        }


    }
}

FirstWeb/Controllers/TimKiemTheoMaController.cs
using FirstWeb.Models;
using FirstWeb.Views;
using Microsoft.AspNetCore.Mvc;

namespace FirstWeb.Controllers
{
    public class TimKiemTheoMaController : Controller
    {
        private readonly IStudentRepository<Student> _studentRepository;
        private readonly IMajorRepository<Major> _majorRepository;

        public TimKiemTheoMaController(IStudentRepository<Student> studentRepository, IMajorRepository<Major> majorRepository)
        {
            this._studentRepository = studentRepository;
            this._majorRepository = majorRepository;
        }
        public async Task<IActionResult> TimKiemTheoMaView([Bind("maNganh, index")] string maNganh, int index)
        {
            IEnumerable<Student> studentList;
            
            if (!string.IsNullOrEmpty(maNganh))
            {
                HttpContext.Session.SetObjectAsJson("Major", maNganh);
                //sử lí tổng trang 
                var totalTask = _studentRepository.GetNumMarjorItemAsync(maNganh);
                var total = await totalTask;
                var endPage = (total % 4 == 0) ? total / 4 : (total / 4) + 1;
                var students = await _studentRepository.GetAllMajorAsync(maNganh, index);
                studentList = students.ToList();
                //truyền dữ liệu
                TempData["endPage2"] = endPage;
                //students = await _studentRepository.GetSearchMaNganhAsync(maNganh);
            }
            else 
            {
                var major = HttpContext.Session.GetObjectFromJson<String>("Major");
                var totalTask = _studentRepository.GetNumMarjorItemAsync(major);
                var total = await totalTask;
                var endPage = (total % 4 == 0) ? total / 4 : (total / 4) + 1;
                var students = await _studentRepository.GetAllMajorAsync(major, index);
                studentList = students.ToList();
                //truyền dữ liệu
                TempData["endPage2"] = endPage;
            }
           
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View(studentList);
        }

    }
}

FirstWeb/Views/TimKiemTheoMa/TimKiemTheoMaView.cshtml
@model IEnumerable<FirstWeb.Models.Student>

@{
    ViewData["Title"] = "Tìm kiếm";
}
<h1>Danh sách sinh viên Tìm kiếm </h1>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.maSV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hoTen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ngaySinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.soDiemCong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.maNganh)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="~/@item.image" style="width: 100px; height: 100px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.maSV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.hoTen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.gioiTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ngaySinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.soDiemCong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.maNganh)
                </td>
                <td>
                    <a asp-controller="Student" asp-action="Edit" asp-route-maSV="@item.maSV">Edit</a> |
                    <a asp-controller="Student" asp-action="Details" asp-route-maSV="@item.maSV">Details</a> |
                    <a asp-controller="Student" asp-action="Delete" asp-route-maSV="@item.maSV">Delete</a>
                </td>
                <td>
                    <form asp-controller="GioHang" asp-action="Add" method="post">
                        <input type="hidden" name="maSV" value="@item.maSV" />
                        <button type="submit" class="w3-button w3-green w3-border">Add</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>
<div id="pagination-container" class="pagination-container" style="display: flex;">
    @if (TempData["endPage2"] != null)
    {
        var endPage = (int)TempData["endPage2"];
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" >Previous</a></li>
                @for (int it = 1; it <= endPage; it++)
                {
                    <li class="page-item"><a asp-controller="TimKiemTheoMa" asp-action="TimKiemTheoMaView" asp-route-index="@it">@it</a></li>
                }
                <li class="page-item"><a class="page-link" >Next</a></li>
            </ul>
        </nav>
    }
</div>

<div>
    <a asp-controller="Student" asp-action="Create">Create New Student</a>
</div>

@* <script>
    function navigateToPage(pageIndex) {
        // Lưu vị trí cuộn hiện tại vào localStorage
        localStorage.setItem('scrollPosition', window.scrollY);
        // Chuyển hướng đến trang với index
        window.location.href = `@Url.Action("TimKiemView", "TimKiem")?index=${pageIndex}`;
    }

    // Khi trang tải lại, khôi phục vị trí cuộn từ localStorage
    window.onload = function () {
        var scrollPosition = localStorage.getItem('scrollPosition');
        if (scrollPosition) {
            window.scrollTo(0, scrollPosition);
            localStorage.removeItem('scrollPosition');
        }
    };
</script> *@