FirstWeb/Controllers/DangNhapController.cs
using Azure.Core;
using FirstWeb.Models;
using FirstWeb.Views;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace FirstWeb.Controllers
{
    public class DangNhapController : Controller
    {
        private readonly ILoginRepository<Login> _loginRepository;
        private readonly IMajorRepository<Major> _majorRepository;
        public DangNhapController(ILoginRepository<Login> loginRepository, IMajorRepository<Major> majorRepository)
        {
            this._loginRepository = loginRepository;
            this._majorRepository = majorRepository;
        }
        public async Task<IActionResult> DangNhapView()
        {
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View();
        }

        [HttpPost, ActionName("CheckLogin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckLogin(string taiKhoan, string matKhau)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(taiKhoan) && !string.IsNullOrEmpty(matKhau))
                {
                    var loginResult = await _loginRepository.checkLogin(taiKhoan, matKhau);

                    if (loginResult != null)
                    {
                        if (loginResult.role)
                        {
                            HttpContext.Session.SetObjectAsJson("User", loginResult);
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            HttpContext.Session.SetObjectAsJson("User", loginResult);
                            return RedirectToAction("LichSuView", "LichSu");
                        }
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Đăng nhập không thành công!";
                    }
                }
            }
            ViewBag.Majors = await _majorRepository.GetNganhAsync();
            return View("DangNhapView");
        }        

    }
}

FirstWeb/Views/DangNhap/DangNhapView.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model FirstWeb.Models.Login
@{
    ViewData["Title"] = "Đăng Nhập";
}
<div class="container">

    <div class="container">
        <form class="form-signin" asp-controller="DangNhap" asp-action="CheckLogin" method="post">
            @Html.AntiForgeryToken()

            <h2 class="form-signin-heading">Đăng Nhập</h2>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="taiKhoan" class="sr-only">Username</label>
                <input asp-for="taiKhoan" type="text" class="form-control" placeholder="Username" name="taiKhoan">
                <span asp-validation-for="taiKhoan" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="matKhau" class="sr-only">Password</label>
                <input asp-for="matKhau" type="password" class="form-control" placeholder="Password" name="matKhau">
                <span asp-validation-for="matKhau" class="text-danger"></span>
            </div>

            <button class="btn btn-lg btn-primary btn-block btn-white" type="submit">Đăng nhập</button>
        </form>
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">
                <strong>@TempData["ErrorMessage"]</strong>
            </div>
        }
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}